"""清洗后的独立随机画师串池。

来源：quicktagcloud artist_nai45_strings 2026.7.10，以及已实测预设配方。
只保留至少 3 个合法 artist 标签、权重不超过 1.5 的组合。
"""

RANDOM_ARTIST_SOURCE = {
    "codex": "artist_nai45_strings",
    "version": "2026.7.10",
    "url": "https://novelai.quicktagcloud.com/?codex=artist_nai45_strings",
}

RANDOM_ARTIST_COMBOS = (
    ('W.O.F 003', 'artist_nai45_strings_0003', 'artist:wolrero, artist:namaonpa, 0.6::artist:bee (deadflow)::, 1.5::artist:solipsist::, artist:vivid_colors'),
    ('W.O.F 004', 'artist_nai45_strings_0004', 'artist:wolrero, artist:namaonpa, 0.6::artist:bee (deadflow)::, 1.5::artist:solipsist::, artist:vivid_colors, artist:amazing'),
    ('W.O.F 005', 'artist_nai45_strings_0005', '0.2::artist:blue_gk::, 0.4::artist:mx2j::, 0.5::artist:ciloranko::, 0.6::artist:mika pikazo::, 0.5::artist:dramz::, artist:96yottea'),
    ('W.O.F 007', 'artist_nai45_strings_0007', '0.3::artist:kidmo::, 0.8::artist:freng::, 1.4::artist:kat (bu-kunn)::, 1.05::artist:sumiyao (amam)::, 1.5::artist:imai akira ::, 1.1::artist:fungi542 ::'),
    ('W.O.F 008', 'artist_nai45_strings_0008', '0.3::artist:toosaka asagi::, 0.3::artist:miv4t::, 0.3::artist:huashijw::, 0.1::artist:quasarcake::, artist:hibioes, artist:konya karasue'),
    ('W.O.F 010', 'artist_nai45_strings_0010', '0.45::artist:pan_(mimi)::, 0.6::artist:skinfang::, 0.7::artist:hoshi_(snacherubi)::, 0.75::artist:comodox::, 0.8::artist:chen_bin::, artist:pale_skin'),
    ('W.O.F 011', 'artist_nai45_strings_0011', '0.5::artist:bacius::, 0.8::artist:qiandaiyiyu::, 0.9::artist:lunch (shin new)::, 1.1::artist:96yottea::, 1.3::artist:dishwasher1910 ::, 1.45::artist:bm94199 ::'),
    ('W.O.F 013', 'artist_nai45_strings_0013', 'artist:chen_bin, artist:sakimichan, artist:imamura_ryou, artist:honnryou_hanaru, artist:ruanjia'),
    ('W.O.F 014', 'artist_nai45_strings_0014', '0.6::artist:wanke::, 0.4::artist:nakddidi::, 0.4::artist:nakamura_hinata::, artist:yoneyama_mai, 0.6::artist:keki_chogyegi::, artist:prism_chromatic_aberration'),
    ('W.O.F 015', 'artist_nai45_strings_0015', 'artist:tianliang_duohe_fangdongye, artist:kaminokefusa, artist:deaver'),
    ('W.O.F 017', 'artist_nai45_strings_0017', 'artist:tianliang_duohe_gangdongye, artist:kaminokefusa, artist:deaver'),
    ('W.O.F 022', 'artist_nai45_strings_0022', 'artist:mankai kaika, 0.2::artist:ebifurya::, 0.8::artist:kanzarin::, artist:sumiyao(amam), 1.2::artist:rong hui::, 0.2::artist:betabeet::'),
    ('W.O.F 027', 'artist_nai45_strings_0027', '1.1::artist:wlop::, 0.8::artist:omone_hokoma_agm::, 0.5::artist:tianliang_duohe_fangdongye::, artist:shiny'),
    ('W.O.F 028', 'artist_nai45_strings_0028', '0.95::artist:opossumachine::, artist:healthy man, 0.9::artist:tianliang duohe fangdongye::, artist:blender_(medium), artist:unity_(medium), artist:vrchat'),
    ('W.O.F 029', 'artist_nai45_strings_0029', '0.9::artist:wlop::, 0.3::artist:domo_(domokizusuki)::, 1.1::artist:au(d_elete)::, artist:best_illumination'),
    ('W.O.F 030', 'artist_nai45_strings_0030', '0.9::artist:wlop::, 0.3::artist:domo_(domokizusuki)::, 1.1::artist:au(d_elete)::, artist:best_illumination, artist:movie_perspective, artist:dynamic_angle'),
    ('W.O.F 031', 'artist_nai45_strings_0031', 'artist:kedama_milk, artist:ciloranko, artist:ask_(askzy), artist:mignon, artist:rhasta, artist:icecake'),
    ('W.O.F 033', 'artist_nai45_strings_0033', 'artist:sawayaka_samehada, artist:pan_(mimi), artist:hoshi_(snacherubi), artist:comodox, artist:chen_bin, artist:suannai_wanzi'),
    ('W.O.F 035', 'artist_nai45_strings_0035', 'artist:dynamic_pose, artist:dynamic_composition, artist:movie_perspective, artist:dynamic_angle, artist:cinematic_angle, artist:dutch_angle'),
    ('W.O.F 036', 'artist_nai45_strings_0036', '1.1::artist:ningen mame::, 0.9::artist:cain(gunnermul)::, 0.75::artist:null(nyanpyoun)::, 0.9::artist:taesi::, 0.7::artist:jtveemo::, 1::artist:blue gk::'),
    ('W.O.F 037', 'artist_nai45_strings_0037', 'artist:ciloranko, artist:sho, artist:sho_lwlw, artist:tianliang_duohe_fangdongye, artist:movie_perspective, artist:dynamic_angle'),
    ('W.O.F 039', 'artist_nai45_strings_0039', 'artist:movie_perspective, artist:dynamic_angle, artist:cinematic_angle, artist:dutch_angle'),
    ('W.O.F 040', 'artist_nai45_strings_0040', 'artist:intricate_details, artist:epic, artist:chiaroscuro, artist:sharp_focus, artist:vibrant_colors, artist:8k'),
    ('W.O.F 041', 'artist_nai45_strings_0041', 'artist:epic, artist:intricate_details, artist:chiaroscuro, artist:murata yusuke, 0.95::artist:ciloranko::, 1.05::artist:tianliang duohe fangdongye::'),
    ('W.O.F 042', 'artist_nai45_strings_0042', 'artist:epic, artist:intricate_details, artist:chiaroscuro, artist:sharp_focus, artist:vibrant_colors, artist:murata yusuke'),
    ('W.O.F 043', 'artist_nai45_strings_0043', 'artist:konya_karasue, artist:wlop, artist:zombie_ke, artist:ciloranko, artist:junpaku_karen, artist:achiki'),
    ('W.O.F 045', 'artist_nai45_strings_0045', 'artist:arato_asato, artist:ratatatat74, artist:eonsang, artist:freng, artist:null_(nyanpyoun), 0.9::artist:ahemaru ::'),
    ('W.O.F 046', 'artist_nai45_strings_0046', 'artist:nyr50ml, artist:candid, artist:colo_(frypan_soul)'),
    ('W.O.F 047', 'artist_nai45_strings_0047', 'artist:nyr50ml, artist:candid, artist:colo_(frypan_soul), artist:reflection_on_glass, artist:lonely_atmosphere, artist:late_night_vibe'),
    ('W.O.F 050', 'artist_nai45_strings_0050', 'artist:ligne_claire, 1.0::artist:t1kosewad::, artist:fkey, artist:t1kosewad, artist:say_hana, artist:kieed'),
    ('W.O.F 052', 'artist_nai45_strings_0052', '1.3::artist:hoshi_(snacherubi)::, 0.9::artist:chen_bin::, 0.7::artist:amashiro_natsuki::, artist:sonao, artist:sparrowl, artist:parsley'),
    ('W.O.F 055', 'artist_nai45_strings_0055', 'artist:kanikama, artist:shinjiro, artist:cha_goma, artist:4_(nakajima4423), artist:mebaru, artist:tanaka_yuuichi'),
    ('W.O.F 056', 'artist_nai45_strings_0056', 'artist:lk149, artist:aog, artist:wagashi_(dagashiya), artist:chen_bin, artist:rebun, artist:motion_lines'),
    ('W.O.F 057', 'artist_nai45_strings_0057', 'artist:ningen_mame, artist:mika_pikazo, artist:reoen, artist:tianliang_duohe_fangdongye, artist:chen_bin, artist:ask_(askzy)'),
    ('W.O.F 058', 'artist_nai45_strings_0058', '1.4::artist:possummachine::, 1.4::artist:Flasso::, 1.2::artist:grimgrim::, 1.2::artist:DAGASI::, 0.4::artist:kakure_eria::, 1.4::artist:tianliang_duohe_fangdongye::'),
    ('W.O.F 059', 'artist_nai45_strings_0059', 'artist:sonao, artist:ssambatea, 0.5::artist:ahemaru::, 1.2::artist:healthyman::, artist:rusellunt, artist:phantom_ix_row'),
    ('W.O.F 060', 'artist_nai45_strings_0060', 'artist:4k, artist:ai-generated, artist:ai-assisted, artist:game_cg, 0.9::artist:ask (askzy)::, artist:thin_drawing_lines'),
    ('W.O.F 061', 'artist_nai45_strings_0061', '1.5::artist:mx2j::, 1.2::artist:ratatatat74 ::, 0.7::artist:tokiame::, 0.5::artist:nyong nyong::, 0.3::artist:usa37107692 ::, artist:cartoonized'),
    ('W.O.F 062', 'artist_nai45_strings_0062', '1.5::artist:shinjiro::, 1.2::artist:takano suzu::, 0.9::artist:namidame::, 1.2::artist:baffu::, 0.8::artist:null (nyanpyoun)::, 0.8::artist:deadnooodles::'),
    ('W.O.F 063', 'artist_nai45_strings_0063', 'artist:junsuina_fujunbutsu, artist:donmin_h, artist:flat_color, artist:big_head, artist:image_macro_(meme), artist:original'),
    ('W.O.F 065', 'artist_nai45_strings_0065', 'artist:webtoon, artist:pixiv, artist:healthyman, 1.4::artist:hizuki akira::, 0.7::artist:freng::, artist:blue gk'),
    ('W.O.F 066', 'artist_nai45_strings_0066', 'artist:reel_(riru), artist:ushikani_kassen, artist:douya_(233), artist:hyuk_(yeayeo), artist:kcccc, artist:misaka_12003-gou'),
    ('W.O.F 067', 'artist_nai45_strings_0067', 'artist:homura_subaru, artist:miyoshi_yoshimi, artist:dayama, artist:nikichen, artist:kimhiro, artist:no_lineart'),
    ('W.O.F 069', 'artist_nai45_strings_0069', '1.2::artist:tianliang_duohe_fangdongye::, 0.2::artist:eonsang::, 1.2::artist:ebora::, 1.4::artist:wow_(cor369)::, 1.2::artist:ratatatat74 ::, 0.8::artist:kidmo::'),
    ('W.O.F 070', 'artist_nai45_strings_0070', '1.5::artist:fymrie::, 1.3::artist:shuri_(84k)::, 0.7::artist:ye_jji::, artist:nonddu, 0.5::artist:modare::, artist:dotori_(seulseul)'),
    ('W.O.F 072', 'artist_nai45_strings_0072', 'artist:merunyaa, artist:mikozin, artist:mizumizuni, artist:fis_(t83192933), artist:naga_u, artist:yuzutei'),
    ('W.O.F 074', 'artist_nai45_strings_0074', 'artist:funamusea, artist:merunyaa, artist:mikozin, artist:mizumizuni, artist:fis_(t83192933), artist:naga_u'),
    ('W.O.F 076', 'artist_nai45_strings_0076', 'artist:artist_collaboration, artist:consistent_characters, 1.1::artist:pottsness::, 1.1::artist:rurudo::, 0.6::artist:chocoan::, 1.1::artist:ciloranko::'),
    ('W.O.F 077', 'artist_nai45_strings_0077', '1.5::artist:nekojira::, 1.5::artist:ratatatat74 ::, artist:ronna, artist:lazyprocrastinator, artist:fpsblyck, artist:tianliang duohe fangdongye'),
    ('W.O.F 079', 'artist_nai45_strings_0079', 'artist:kunaboto, 1.35::artist:feipin zhanshi::, 1.5::artist:2n5::, 1.3::artist:mikozin::, artist:mangmoongming, artist:blender_(medium)'),
    ('W.O.F 081', 'artist_nai45_strings_0081', 'artist:heripiro, artist:omochi_monaka, artist:kyuumura, artist:tianliang_duohe_fangdongye, artist:fenrir_(fenriluuu), 0.9::artist:patzzi::'),
    ('W.O.F 082', 'artist_nai45_strings_0082', '1.2::artist:sonao::, 0.9::artist:try (lsc)::, 0.8::artist:gaou (umaiyo puyoman)::, 0.8::artist:healthyman::, 0.7::artist:wagashi (dagashiya)::, 0.6::artist:null (nyanpyoun)::'),
    ('W.O.F 083', 'artist_nai45_strings_0083', '1.4::artist:min_(120716)::, 1.1::artist:ming_zhentan_allk::, 0.7::artist:ham_melon_(iloha_24)::, 0.4::artist:noyu_(noyu23386566)::, 0.4::artist:omone_hokoma_agm::'),
    ('W.O.F 084', 'artist_nai45_strings_0084', 'artist:bm94199, artist:wo_jiushi_kanbudong, artist:nixeu, artist:slash_(slash-soft), artist:billyhhyb, artist:ruanjia'),
    ('W.O.F 088', 'artist_nai45_strings_0088', '[[artist:ritzchrono]], [[[artist:wagashi (dagashiya)]]], [[artist:mx2j]], artist:shiny_skin, artist:humid_skin'),
    ('W.O.F 089', 'artist_nai45_strings_0089', 'artist:ratatatat74, artist:tianliang_duohe_fangdongye, artist:sqloveraven, artist:yum_606, artist:ningen_mame, artist:lemon89h'),
    ('W.O.F 090', 'artist_nai45_strings_0090', 'artist:sawayaka_samehada, artist:pan_(mimi), artist:hoshi_(snacherubi), artist:comodox, artist:chen_bin, artist:suaynnai_wanzi'),
    ('W.O.F 091', 'artist_nai45_strings_0091', '[artist:sho_(sho_lwlw)], [artist:baku-p], [artist:tianliang_duohe_fangdongye], [artist:chen_bin], artist:motion_lines'),
    ('W.O.F 094', 'artist_nai45_strings_0094', 'artist:expert_shading, artist:chen_bin, artist:pumpkinspicelatte, artist:au_(d_elete), artist:modare, artist:ebifurya'),
    ('W.O.F 095', 'artist_nai45_strings_0095', 'artist:highly_finished, artist:Character_Study, artist:fine_fabric_emphasis, artist:noise_reduction, artist:chromatic_aberration, artist:cinematic_angle'),
    ('W.O.F 097', 'artist_nai45_strings_0097', 'artist:amazing, artist:wolrero, artist:namaonpa, 0.6::artist:bee (deadflow)::, 1.5::artist:solipsist::, artist:vivid_colors'),
    ('W.O.F 098', 'artist_nai45_strings_0098', 'artist:aoi_sora_no_neosphere, artist:black_outline, artist:thick_outline, artist:16k_resolution, artist:ultra_high_resolution, artist:takega_hinata'),
    ('W.O.F 100', 'artist_nai45_strings_0100', 'artist:1nupool, artist:movie_perspective, artist:dynamic_angle, artist:cinematic_angle, artist:dutch_angle'),
    ('W.O.F 101', 'artist_nai45_strings_0101', 'artist:agoto, artist:kedama milk, {artist:nixeu}, artist:tianliang duohe fangdongye, artist:nakimayo, artist:Chen bin'),
    ('W.O.F 102', 'artist_nai45_strings_0102', 'artist:ask (askzy), 0.9::artist:jtveemo::, 0.9::artist:cain (gunnermul)::, 0.8::artist:ningen mame::, 1.2::artist:null (nyanpyoun)::, artist:terada tera'),
    ('W.O.F 103', 'artist_nai45_strings_0103', 'artist:ciloranko, 0.95::artist:sho_(sho_lwlw)::, 0.91::artist:tianliang_duohe_fangdongye::, 0.74::artist:kani_biimu::, artist:movie_perspective, artist:dynamic_angle'),
    ('W.O.F 106', 'artist_nai45_strings_0106', 'artist:fkey, artist:massakasama, artist:zirarval, 1.5::artist:solipsist ::, artist:dark_room, artist:bedroom'),
    ('W.O.F 107', 'artist_nai45_strings_0107', 'artist:healthyman, 1.1::artist:yamamoto souichirou::, 0.9::artist:tianliang duohe fangdongye::, artist:imamura ryou, artist:ronna, 1.2::artist:maud0239 ::'),
    ('W.O.F 108', 'artist_nai45_strings_0108', 'artist:lativi_(ltv60), 0.85::artist:sincos::, 0.7::artist:yakihebi::, artist:healthyman, 0.6::artist:typehatena::, 1.2::artist:yazawa_oke::'),
    ('W.O.F 110', 'artist_nai45_strings_0110', 'artist:massakasama, 0.6::artist:fenrir_(fenriluuu)::, 0.5::artist:amonitto::, 0.6::artist:op na yarou::, 0.4::artist:channel_(caststation)::'),
    ('W.O.F 111', 'artist_nai45_strings_0111', 'artist:nanmokaken, artist:sho_(sho_lwlw), artist:tianliang_duohe_fangdongye, [artist:shiratamaco], [artist:nekoshoko], artist:blurry'),
    ('W.O.F 113', 'artist_nai45_strings_0113', 'artist:rella, artist:dark_cinematic_atmosphere, artist:high_contrast, artist:silhouette, artist:mysterious, artist:divine'),
    ('W.O.F 114', 'artist_nai45_strings_0114', 'artist:yalmyu, artist:ruriri, artist:healthyman, 0.8::artist:urotsuki (ku9625)::, artist:tianliang_duohe_fangdongye, artist:kele mimi'),
    ('W.O.F 115', 'artist_nai45_strings_0115', 'artist:yuefuku1224, artist:moo_n_moko, artist:chunye_haruka, artist:memes, artist:upper_body, artist:close-up'),
    ('W.O.F 120', 'artist_nai45_strings_0120', 'artist:hyper_detail, artist:8k_render, 0.8::artist:gogalking ::, 1::artist:yamamoto souichirou ::, 0.8::artist:ratatatat74 ::, 0.4::artist:ciloranko ::'),
    ('W.O.F 121', 'artist_nai45_strings_0121', 'artist:nopossumachine, [artist:amonitto], artist:movie_perspective, artist:dynamic_angle, artist:cinematic_angle, artist:dutch_angle'),
    ('W.O.F 122', 'artist_nai45_strings_0122', 'artist:precise_geometry, artist:lativi_(ltv60), 0.85::artist:sincos::, 0.7::artist:yakihebi::, artist:healthyman, 0.6::artist:typehatena::'),
    ('W.O.F 123', 'artist_nai45_strings_0123', '1.2::artist:vanripper::, 0.8::artist:batrobin_k::, 0.5::artist:take_(illustrator)::, 0.5::artist:j.k.::, 0.4::artist:jtveemo::, 0.3::artist:senmu_(0107)::'),
    ('W.O.F 124', 'artist_nai45_strings_0124', 'artist:blue_archive, artist:game_cg, artist:movie_perspective, artist:dynamic_angle, artist:cinematic_angle, artist:dutch_angle'),
    ('W.O.F 125', 'artist_nai45_strings_0125', 'artist:blue_archive, artist:game_cg, artist:extremely_vibrant_colors, artist:magical_atmosphere, artist:dynamic_composition'),
    ('W.O.F 126', 'artist_nai45_strings_0126', '[[[artist:bilibili_xiaolu]]], artist:sfw, artist:lens_flare, artist:dutch_angle, artist:Luminous_particle, artist:indoors'),
    ('W.O.F 129', 'artist_nai45_strings_0129', 'artist:deyui, artist:pumpkinspicelatte, artist:tianliang_duohe_fangdongye, artist:wagashi_(dagashiya), artist:healthyman, artist:hxxg'),
    ('W.O.F 131', 'artist_nai45_strings_0131', 'artist:fur_dataset, artist:pale_color, artist:skin_luster, artist:glossy_skin, artist:sunlight, artist:drive_shot'),
    ('W.O.F 133', 'artist_nai45_strings_0133', 'artist:hanekoto, artist:wlop, artist:toosaka_asagi, artist:himitsu_(hi_mi_tsu_2), artist:mignon, artist:misaki_kurehito'),
    ('W.O.F 136', 'artist_nai45_strings_0136', 'artist:ichigoyama, artist:ashima_(roro046), artist:rella, artist:onineko, artist:purple_light, artist:black_hole'),
    ('W.O.F 137', 'artist_nai45_strings_0137', 'artist:ichigoyama, artist:ashima_(roro046), artist:rella, artist:onineko, artist:pastel_colors, artist:contour_deepening'),
    ('W.O.F 138', 'artist_nai45_strings_0138', 'artist:magazine_cover, artist:dutch_angle, artist:shiny_skin, artist:pastel_colors, artist:natural, artist:commission'),
    ('W.O.F 139', 'artist_nai45_strings_0139', 'artist:anime, artist:dynamic_angle, artist:beautiful_eyes, artist:deep_and_clear_pupils, artist:sparkling_highlights, artist:glossy_reflection'),
    ('W.O.F 140', 'artist_nai45_strings_0140', 'artist:very_awa, artist:ultra-high_resolution, artist:masterful_details, artist:HDR, artist:8K, artist:high_detail_RAW_color_art'),
    ('W.O.F 142', 'artist_nai45_strings_0142', 'artist:konya_karasue, artist:yd_(orange_maru), artist:au_ito, artist:betabeet, artist:pottsness, artist:houkisei'),
    ('W.O.F 143', 'artist_nai45_strings_0143', '0.01::artist:noyu_(noyu23386566) ::, artist:ningen mame, artist:min_(120716), artist:ciloranko, artist:rella, artist:konya_karasue'),
    ('W.O.F 145', 'artist_nai45_strings_0145', 'artist:pastel_color, artist:flat_color, artist:no_lineart, artist:super_deformed'),
    ('W.O.F 146', 'artist_nai45_strings_0146', 'artist:motion_lines, artist:motion_blur, artist:shiny_skin, artist:high_detail, artist:commission, 1.4::artist:john_kafka::'),
    ('W.O.F 147', 'artist_nai45_strings_0147', 'artist:wanke, artist:nokoru_sora, artist:microsoft_paint_(medium), artist:flat_color, artist:sketch, artist:clean_lines'),
    ('W.O.F 150', 'artist_nai45_strings_0150', 'artist:wanke, 0.73::artist:starstruckdonl::, 0.7::artist:dayama::, 0.3::artist:96yottea::, artist:nokoru_sora, artist:microsoft_paint_(medium)'),
    ('W.O.F 151', 'artist_nai45_strings_0151', 'artist:wanke, artist:starstruckdonl, artist:dayama, artist:96yottea, artist:nokoru_sora, artist:microsoft_paint_(medium)'),
    ('W.O.F 152', 'artist_nai45_strings_0152', 'artist:ningen_mame, artist:mika_pikazo, artist:reoen, artist:tianliang_duohe_fangdongye, artist:ask_(askzy), artist:kantoku'),
    ('W.O.F 166', 'artist_nai45_strings_0166', 'artist:high_detail, artist:commission, artist:shiny_skin, artist:motion_blur, artist:motion_lines, artist:karyln'),
    ('W.O.F 168', 'artist_nai45_strings_0168', 'artist:ryanreos, artist:rong_hui, artist:ru_zhai, artist:blobcg, artist:dab_neko, artist:ukai_saki'),
    ('W.O.F 171', 'artist_nai45_strings_0171', 'artist:takei_ooki, artist:ame_usari, artist:karory, artist:kazutake_hazano, [artist:houkisei], [artist:shirosei mochi]'),
    ('W.O.F 172', 'artist_nai45_strings_0172', 'artist:sfw, artist:top_rated, artist:chen_bin, artist:fuzichoco, artist:jima, artist:rei_(sanbonzakura)'),
    ('W.O.F 173', 'artist_nai45_strings_0173', 'artist:sfw, artist:top_rated, artist:onineko, artist:akizero1510, artist:wanke, [[artist:akakura]]'),
    ('W.O.F 175', 'artist_nai45_strings_0175', 'artist:ver2025, artist:yukie_(kusaka_shi), 1.3::artist:turisasu::, 1.2::artist:iisan_(zvemsv420vuqzzb)::, 0.9::artist:freng::, 1.1::artist:ie_(raarami)::'),
    ('W.O.F 176', 'artist_nai45_strings_0176', 'artist:4k, artist:kawaii, artist:soft_pastel_linearts, artist:large_highlights, artist:light_colored_eyes, artist:cozy_atmosphere'),
    ('W.O.F 178', 'artist_nai45_strings_0178', '0.8::artist:dorontabi::, 1.1::artist:bongnom::, 1.1::artist:azmira1534815 ::, 0.9::artist:ame_(uten_cancel)::, 0.6::artist:healthyman::, 0.6::artist:sincos::'),
    ('W.O.F 179', 'artist_nai45_strings_0179', '0.5::artist:yukie_(kusaka_shi)::, 0.75::artist:pumpkinspicelatte::, 1::artist:villainchin::, 0.5::artist:kakure_eria::, 0.5::artist:lolo (kemonono)::, 0.3::artist:blvefo9::'),
    ('W.O.F 180', 'artist_nai45_strings_0180', 'artist:blue_theme, 1.16::artist:kedama milk::, 0.86::artist:mika pikazo::'),
    ('W.O.F 181', 'artist_nai45_strings_0181', 'artist:blue_theme, 1.16::artist:kedama milk::, 0.86::artist:mika pikazo::, artist:dynamic_pose, artist:dynamic_composition, artist:movie_perspective'),
    ('W.O.F 182', 'artist_nai45_strings_0182', 'artist:hyper_detail, artist:8k_render, 1.1::artist:yamamoto souichirou ::, 0.9::artist:tianliang duohe fangdongye ::, 1.2::artist:maud0239 ::, artist:expert_shading'),
    ('W.O.F 184', 'artist_nai45_strings_0184', 'artist:game_cg, artist:iroshira_skb, 0.8::artist:cool-kyou_shinja::, 0.8::artist:zankuro::, artist:isemagu, 0.4::artist:musouzuki::'),
    ('W.O.F 185', 'artist_nai45_strings_0185', 'artist:chen_bin, artist:pumpkinspicelatte, artist:au_(delete), artist:modare, artist:ebifurya, artist:wlop'),
    ('W.O.F 187', 'artist_nai45_strings_0187', 'artist:sonao, 1.1::artist:healthyman::, artist:sparrowl, artist:wagashi_(dagashiya), artist:freng, artist:parsley'),
    ('W.O.F 188', 'artist_nai45_strings_0188', 'artist:anime_screenshot, artist:amazing_angle, artist:perspective, artist:lens_flare, artist:blurry, artist:misawa_hiroshi'),
    ('W.O.F 189', 'artist_nai45_strings_0189', 'artist:hyper_detail, artist:8k_render, 0.8::artist:gogalking::, artist:yamamoto souichirou, 0.8::artist:ratatatat74 ::, 0.4::artist:ciloranko::'),
    ('W.O.F 191', 'artist_nai45_strings_0191', 'artist:vivid_color, artist:cinematic_composition, artist:no_lineart, artist:no_outline, artist:bad_anatomy, artist:channel_(caststation)'),
    ('W.O.F 192', 'artist_nai45_strings_0192', 'artist:sonao, artist:healthyman, artist:sparrowl, artist:wagashi_(dagashiya), artist:freng, artist:parsley'),
    ('W.O.F 193', 'artist_nai45_strings_0193', 'artist:yao_liao_wang, artist:fkey, artist:meinoss, artist:some1else45, artist:akipeko, artist:chuck_(harfmoondark)'),
    ('W.O.F 194', 'artist_nai45_strings_0194', 'artist:blender_(medium), artist:silky_skin, artist:high_detail, artist:duplicate, artist:mx2j'),
    ('W.O.F 196', 'artist_nai45_strings_0196', 'artist:yukie_(kusaka_shi), artist:chen_bin, artist:tsubasa_tsubasa, artist:bee_(deadflow), artist:location'),
    ('W.O.F 197', 'artist_nai45_strings_0197', '{artist:rubi-sama}, {artist:rurudo}, artist:usashiro_mani, artist:ciloranko, [artist:houkisei], [artist:ame_usari]'),
    ('W.O.F 199', 'artist_nai45_strings_0199', '{{artist:yoneyama mai}}, {artist:konya karasue}, {artist:z3zz4}, artist:melancholic, artist:sidelight, artist:chromatic_aberration'),
    ('W.O.F 200', 'artist_nai45_strings_0200', 'artist:highest_resolution, artist:perfect_anatomy, artist:8K, artist:realism, artist:vibrant_colors, artist:delicate_color'),
    ('梦神NAI4.5F画风合集 0001', 'mengshen_pack-0001', 'artist:kagura_nana, artist:gomzi, 1.1::artist:WANKE::, 1.1::artist:modare::, 1.3::artist:au (d elete)::, artist:impasto'),
    ('梦神NAI4.5F画风合集 0002', 'mengshen_pack-0002', 'artist:kagura_nana, artist:yukie (kusaka shi), artist:minami (minamijkol), artist:healthyman, artist:typehatena, artist:tsubasa_tsubasa'),
    ('梦神NAI4.5F画风合集 0003', 'mengshen_pack-0003', 'artist:kagura_nana, 0.5::artist:kakure eria::, 1::artist:freng::, 1.2::artist:dorontabi::, 1::artist:kanzarin::, artist:8k_wallpaper'),
    ('梦神NAI4.5F画风合集 0004', 'mengshen_pack-0004', 'artist:kagura_nana, 1.2::artist:pochi (pochi-goya) ::, 0.8::artist:channel (caststation) ::, 0.4::artist:zyugoya ::, 0.6::artist:ankoman ::, 0.6::artist:10mo ::'),
    ('梦神NAI4.5F画风合集 0005', 'mengshen_pack-0005', 'artist:kagura_nana, 1.5::artist:teshima nari ::, 1.2::artist:ishigaki takashi ::, 1.3::artist:ramanda ::, 1.1::artist:sohn woohyoung ::, 1.1::artist:channel (caststation) ::'),
    ('梦神NAI4.5F画风合集 0006', 'mengshen_pack-0006', 'artist:kagura_nana, 1.45::artist:gogalking::, 1.3::artist:xipa::, 1.4::artist:murata yusuke::, 1.35::artist:2n5 ::, 1.25::artist:henriiku_(ahemaru)::'),
    ('梦神NAI4.5F画风合集 0007', 'mengshen_pack-0007', 'artist:kagura_nana, artist:misaka_12003-gou, artist:myabit, artist:momokumo, artist:ie_(raarami), artist:eonsang'),
    ('梦神NAI4.5F画风合集 0008', 'mengshen_pack-0008', 'artist:kagura_nana, 1.5::artist:ningen_mame ::, 1.2::artist:henreader ::, 1.2::artist:horikoshi_kouhei ::, 1.2::artist:murata yuusuke ::, 1.5::artist:strongbana ::'),
    ('梦神NAI4.5F画风合集 0009', 'mengshen_pack-0009', 'artist:kagura_nana, artist:konya_karasue, artist:wlop, artist:zombie_ke, artist:ciloranko, artist:junpaku_karen'),
    ('梦神NAI4.5F画风合集 0010', 'mengshen_pack-0010', 'artist:kagura_nana, artist:kunaboto, 1.35::artist:feipin zhanshi::, 1.5::artist:2n5::, 1.3::artist:mikozin::, artist:mangmoongming'),
    ('梦神NAI4.5F画风合集 0011', 'mengshen_pack-0011', 'artist:kagura_nana, artist:artist_cg, 0.2::artist:yamamoto souichirou ::, 0.2::artist:kawakami rokkaku ::, 0.2::artist:tianliang duohe fangdongye ::, 0.4::artist:kahlua (artist) ::'),
    ('梦神NAI4.5F画风合集 0012', 'mengshen_pack-0012', 'artist:kagura_nana, 0.4::artist:tianliang duohe fangdongye::, 0.8::artist:teshima_nari ::, 1.2::artist:kazuho iwamoto::, 0.9::artist:hyocorou::, 1.0::artist:inoue kiyoshirou::'),
    ('梦神NAI4.5F画风合集 0014', 'mengshen_pack-0014', 'artist:kagura_nana, 0.9::artist:gomennasai::, 1.1::artist:mannack::, 1.2::artist:horideiyasumi::, 1.3::artist:hiro (dismaless)::, 0.9::artist:healthyman::'),
    ('梦神NAI4.5F画风合集 0015', 'mengshen_pack-0015', 'artist:kagura_nana, artist:higashiyama_shou, 0.5::artist:mizumizuni ::, 0.6::artist:shengtian ::, 0.8::artist:loffo ::, artist:commission'),
    ('梦神NAI4.5F画风合集 0016', 'mengshen_pack-0016', 'artist:kagura_nana, 0.55::artist:m-da s-tarou ::, 0.51::artist:toraishi 666 ::, 1.2::artist:onono imoko ::, 1.49::artist:sugoihi ::, artist:8k_wallpaper'),
    ('梦神NAI4.5F画风合集 0017', 'mengshen_pack-0017', 'artist:kagura_nana, 1.5::artist:sakura_m_fsn::, 0.5::artist:evan_lee ::, artist:8k_wallpaper, artist:high_resolution, artist:intricate_details'),
    ('梦神NAI4.5F画风合集 0018', 'mengshen_pack-0018', 'artist:kagura_nana, 1.2::artist:lativi::, 0.6::artist:wagashi (dagashiya)::, 1.2::artist:yamamoto souichirou ::, 0.6::artist:muchi_maro::, artist:8k_wallpaper'),
    ('梦神NAI4.5F画风合集 0019', 'mengshen_pack-0019', 'artist:kagura_nana, artist:indie_virtual_youtuber, 0.2::artist:blue_gk::, artist:horosuke, artist:horikoshi_kouhei, artist:ushikani_kassen'),
    ('梦神NAI4.5F画风合集 0021', 'mengshen_pack-0021', 'artist:kagura_nana, artist:indie_virtual_youtuber, artist:oekaki, artist:jaggy_lines, 0.9::artist:asanagi ::, artist:lunch_(shin_new)'),
    ('梦神NAI4.5F画风合集 0022', 'mengshen_pack-0022', 'artist:kagura_nana, 0.8::artist:hito_komoru ::, 1.3::artist:henken ::, 1.5::artist:pigeon666 ::, artist:ie_(raarami), artist:solipsist'),
    ('梦神NAI4.5F画风合集 0024', 'mengshen_pack-0024', 'artist:kagura_nana, 1.2::artist:gogalking::, 1.3::artist:seramikku ::, 0.8::artist:rei_(sanbonzakura) ::, 1.1::artist:krenz::, 0.9::artist:sparrowl::'),
    ('梦神NAI4.5F画风合集 0026', 'mengshen_pack-0026', 'artist:kagura_nana, 0.6::artist:shinjiro::, 0.7::artist:ie (raarami)::, 0.7::artist:healthyman::, artist:8k_wallpaper, artist:high_resolution'),
    ('梦神NAI4.5F画风合集 0027', 'mengshen_pack-0027', 'artist:kagura_nana, 1.3::artist:imamura_ryou::, artist:wagashi (dagashiya), 1.2::artist:abmayo::, artist:puddinghomhom, artist:waterkuma'),
    ('梦神NAI4.5F画风合集 0028', 'mengshen_pack-0028', 'artist:kagura_nana, artist:lativi_(ltv60), 0.85::artist:sincos::, 0.7::artist:yakihebi::, artist:healthyman, 0.6::artist:typehatena::'),
    ('梦神NAI4.5F画风合集 0029', 'mengshen_pack-0029', 'artist:kagura_nana, 0.25::artist:misaka 12003-gou ::, 0.5::artist:mika pikazo ::, 0.8::artist:ratatatat74 ::, 1.2::artist:gogalking ::, 1.3::artist:murata yuusuke ::'),
    ('梦神NAI4.5F画风合集 0030', 'mengshen_pack-0030', 'artist:kagura_nana, artist:indie_virtual_youtuber, 1.5::artist:imigimuru ::, 1.1::artist:sohn woohyoung ::, 1.5::artist:inoue kiyoshirou ::, 1.1::artist:gogalking ::'),
    ('梦神NAI4.5F画风合集 0031', 'mengshen_pack-0031', 'artist:kagura_nana, artist:healthyman, artist:wagashi (dagashiya), 1.5::artist:muchi maro::, artist:8k_wallpaper, artist:high_resolution'),
    ('梦神NAI4.5F画风合集 0032', 'mengshen_pack-0032', 'artist:kagura_nana, artist:indie_virtual_youtuber, artist:oekaki, artist:jaggy_lines, artist:cel_shading, 0.9::artist:asanagi ::'),
    ('梦神NAI4.5F画风合集 0033', 'mengshen_pack-0033', 'artist:kagura_nana, artist:indie_virtual_youtuber, artist:hews, 0.7::artist:gogalking::, 1.1::artist:nora higuma::, artist:hatching_(texture)'),
    ('梦神NAI4.5F画风合集 0034', 'mengshen_pack-0034', 'artist:kagura_nana, artist:wagashi_(dagashiya), artist:ikr_(artist), artist:horikoshi_kouhei, artist:9is, artist:drunkoak'),
    ('梦神NAI4.5F画风合集 0035', 'mengshen_pack-0035', 'artist:kagura_nana, 0.6::artist:freng ::, 1.5::artist:ningen_mame ::, 0.4::artist:ratatatat74 ::, 1.2::artist:imigimuru ::, 0.4::artist:strongbana ::'),
    ('梦神NAI4.5F画风合集 0036', 'mengshen_pack-0036', 'artist:kagura_nana, artist:sketch, 1.2::artist:nyantcha::, 0.3::artist:freng::, artist:nonco, artist:low_opacity_lines.'),
    ('梦神NAI4.5F画风合集 0037', 'mengshen_pack-0037', 'artist:kagura_nana, artist:indie_virtual_youtuber, 1.5::artist:nao_(syn_eaa)::, 1.5::artist:mx2j ::, 1.5::artist:pigeon666 ::, 0.5::artist:waterkuma::'),
    ('梦神NAI4.5F画风合集 0038', 'mengshen_pack-0038', 'artist:kagura_nana, artist:mochirong, artist:healthyman, artist:etchi_inoha_sukidesuka, artist:wang-xi, artist:lm7_(op-center)'),
    ('梦神NAI4.5F画风合集 0039', 'mengshen_pack-0039', 'artist:kagura_nana, artist:jaggy_lines, artist:oekaki, 1.2::artist:nyantcha::, 0.3::artist:freng::, artist:nonco'),
    ('梦神NAI4.5F画风合集 0040', 'mengshen_pack-0040', 'artist:kagura_nana, artist:healthyman, [artist:tianliang duohe fangdongye], artist:jyt, artist:matcha (mattyan), [artist:menthako]'),
    ('梦神NAI4.5F画风合集 0041', 'mengshen_pack-0041', 'artist:kagura_nana, 0.6::artist:kakure_eria ::, 0.75::artist:wagashi_(dagashiya) ::, 0.6::artist:tianliang_duohe_fangdongye ::, 1.2::artist:hyocorou ::, 1.2::artist:jp06_(orangemaru) ::'),
    ('梦神NAI4.5F画风合集 0042', 'mengshen_pack-0042', 'artist:kagura_nana, 1.5::artist:hassan (sink916)::, 0.3::artist:gogalking::, 0.4::artist:shinjiro::, artist:8k_wallpaper, artist:high_resolution'),
    ('梦神NAI4.5F画风合集 0043', 'mengshen_pack-0043', 'artist:kagura_nana, 1.2::artist:ishigaki takashi ::, 0.8::artist:inoue kiyoshirou ::, 0.9::artist:sohn woohyoung ::, 1.1::artist:gogalking ::, 0.6::artist:ie (raarami) ::'),
    ('梦神NAI4.5F画风合集 0044', 'mengshen_pack-0044', 'artist:kagura_nana, artist:healthyman, artist:mirei, artist:kincora, artist:yd_(orange_maru), artist:yunsang'),
    ('梦神NAI4.5F画风合集 0046', 'mengshen_pack-0046', 'artist:kagura_nana, artist:neko_blow, artist:null_(nyanpyoun), 1.4::artist:ogipote::, artist:wlop, artist:musouzuki'),
    ('梦神NAI4.5F画风合集 0047', 'mengshen_pack-0047', 'artist:kagura_nana, 1.2::artist:yamamoto souichirou ::, 0.7::artist:ciloranko ::, 1.0::artist:channel (caststation)::, 1.1::artist:ratatatat74 ::, 1.1::artist:gogalking ::'),
    ('梦神NAI4.5F画风合集 0048', 'mengshen_pack-0048', 'artist:kagura_nana, 1.2::artist:ishigaki takashi ::, 1.3::artist:ramanda ::, 1.1::artist:sohn woohyoung ::, 1.1::artist:gogalking ::, 0.6::artist:ie (raarami) ::'),
    ('梦神NAI4.5F画风合集 0050', 'mengshen_pack-0050', 'artist:kagura_nana, artist:artist_cg, 0.8::artist:kahlua (artist) ::, 1.2::artist:blue borscht ::, 0.8::artist:sonao ::, 1.2::artist:sparrowl ::'),
    ('梦神NAI4.5F画风合集 0051', 'mengshen_pack-0051', 'artist:kagura_nana, artist:nawakena, artist:noeru, artist:yoneyama mai, artist:1.8, artist:gogalking'),
    ('梦神NAI4.5F画风合集 0052', 'mengshen_pack-0052', 'artist:kagura_nana, 1.5::artist:gogalking::, 1.1::artist:krenz::, 1.2::artist:sparrowl::, 1.1::artist:solipsist::, 1.3::artist:jima::'),
    ('梦神NAI4.5F画风合集 0053', 'mengshen_pack-0053', 'artist:kagura_nana, artist:game_cg, artist:kaisen_chuui, artist:sushispin, 1.5::artist:kawakami rokkaku::, 1.1::artist:jp06 ::'),
    ('梦神NAI4.5F画风合集 0054', 'mengshen_pack-0054', 'artist:kagura_nana, artist:film_grain, artist:kunaboto, 1.5::artist:2n5 ::, artist:flat_color, artist:blender_(medium)'),
    ('梦神NAI4.5F画风合集 0055', 'mengshen_pack-0055', 'artist:kagura_nana, artist:ulrich_(tagaragakuin), artist:null_(nyanpyoun), artist:misaka_12003-gou, artist:shiokonbu, 1.25::artist:ikeuchi tanuma ::'),
    ('梦神NAI4.5F画风合集 0056', 'mengshen_pack-0056', 'artist:kagura_nana, 1.2::artist:yamamoto souichirou ::, 0.7::artist:ciloranko ::, 1.3::artist:channel (caststation)::, 1.1::artist:ratatatat74 ::, 1.1::artist:gogalking ::'),
    ('梦神NAI4.5F画风合集 0057', 'mengshen_pack-0057', 'artist:kagura_nana, 1::artist:ie (raarami) ::, 0.4::artist:yamamoto souichirou ::, artist:sos adult, artist:ama_mitsuki, 0.4::artist:beautiful gunbari ::'),
    ('梦神NAI4.5F画风合集 0058', 'mengshen_pack-0058', 'artist:kagura_nana, artist:indie_virtual_youtuber, artist:flat_color, artist:aliasing, artist:jaggy_lines, artist:asanagi'),
    ('梦神NAI4.5F画风合集 0059', 'mengshen_pack-0059', 'artist:kagura_nana, 1.5::artist:bone nigi ::, 1.5::artist:blupixl ::, artist:no_lineart, artist:jaggy_lines, artist:smooth_gradient'),
    ('梦神NAI4.5F画风合集 0061', 'mengshen_pack-0061', 'artist:kagura_nana, 0.6::artist:parsley-f::, 1.4::artist:deyui::, artist:ayuma_sayu, 1.5::artist:onineko::, artist:momoko_(momopoco)'),
    ('梦神NAI4.5F画风合集 0062', 'mengshen_pack-0062', 'artist:kagura_nana, [artist:healthyman], artist:ai-generated, artist:8k_wallpaper, artist:high_resolution, artist:intricate_details'),
    ('梦神NAI4.5F画风合集 0063', 'mengshen_pack-0063', 'artist:kagura_nana, 0.4::artist:jj.jj ::, 0.6::artist:shirabe shiki ::, 0.8::artist:neko (pixiv28238559) ::, 1.0::artist:iisan (zvemsv420vuqzzb) ::, 1.2::artist:terasu mc ::'),
    ('梦神NAI4.5F画风合集 0064', 'mengshen_pack-0064', 'artist:kagura_nana, 1.1::artist:teshima nari::, artist:kunaboto, 1.2::artist:lonklink::, 1.35::artist:feipin zhanshi::, 0.8::artist:mutou mato::'),
    ('梦神NAI4.5F画风合集 0065', 'mengshen_pack-0065', '1.4::artist:mika pikazo::, 1.35::artist:blue gk::, 1.3::artist:chamchami::, 1.2::artist:healthyman::, 0.9::artist:pepe (jonasan)::, artist:ink(medium)'),
    ('梦神NAI4.5F画风合集 0066', 'mengshen_pack-0066', 'artist:kagura_nana, artist:oekaki, artist:jaggy_lines, 0.5::artist:ciloranko::, 0.8::artist:muchi maro::, 1.2::artist:henriiku (ahemaru)::'),
    ('梦神NAI4.5F画风合集 0067', 'mengshen_pack-0067', 'artist:kagura_nana, artist:ohisashiburi, 1.2::artist:ie (raarami)::, 1.5::artist:hyocorou::, 0.7::artist:ergot (erugotto)::, 1.2::artist:xiaoluo xl (xlnosearch)::'),
    ('梦神NAI4.5F画风合集 0068', 'mengshen_pack-0068', 'artist:kagura_nana, 0.2::artist:blue gk::, artist:horosuke, artist:horikoshi kouhei, artist:ushikani kassen, 0.8::artist:cola gotouryouta::'),
    ('梦神NAI4.5F画风合集 0069', 'mengshen_pack-0069', 'artist:kagura_nana, artist:8k_wallpaper, artist:high_resolution, artist:intricate_details, artist:4k, artist:stunning_composition'),
    ('梦神NAI4.5F画风合集 0070', 'mengshen_pack-0070', 'artist:kagura_nana, artist:indie_virtual_youtuber, 1.2::artist:ishigaki takashi ::, 1.3::artist:ramanda ::, 1.1::artist:sohn woohyoung ::, 1.1::artist:gogalking ::'),
    ('梦神NAI4.5F画风合集 0073', 'mengshen_pack-0073', 'artist:kagura_nana, 1.3::artist:teshima nari ::, 1.2::artist:ishigaki takashi ::, 1.3::artist:ramanda ::, 1.1::artist:sohn woohyoung ::, 1.1::artist:channel (caststation) ::'),
    ('梦神NAI4.5F画风合集 0074', 'mengshen_pack-0074', 'artist:kagura_nana, artist:healthyman, [[[artist:kahlua(artist)]]], {artist:wagashi_(dagashiya)}, artist:8k_wallpaper, artist:high_resolution'),
    ('梦神NAI4.5F画风合集 0075', 'mengshen_pack-0075', 'artist:kagura_nana, 1.5::artist:gogalking ::, 0.9::artist:ayuma sayu ::, artist:ratatatat74, artist:eonsang, artist:petenshi_(dr._vermilion)'),
    ('梦神NAI4.5F画风合集 0076', 'mengshen_pack-0076', 'artist:kagura_nana, artist:indie_virtual_youtuber, artist:nyantcha, artist:oekakizuki, artist:chela77, artist:hyouuma'),
    ('梦神NAI4.5F画风合集 0078', 'mengshen_pack-0078', 'artist:kagura_nana, artist:indie_virtual_youtuber, 1.5::artist:imigimuru ::, 1.1::artist:sohn woohyoung ::, 1.3::artist:ushikani kassen ::, 1.1::artist:gogalking ::'),
    ('梦神NAI4.5F画风合集 0079', 'mengshen_pack-0079', 'artist:kagura_nana, 0.3::artist:yamamoto souichirou ::, 0.5::artist:muchi maro ::, 0.6::artist:horikoshi kouhei ::, 1.4::artist:ronna ::, 1.5::artist:3774. ::'),
    ('梦神NAI4.5F画风合集 0080', 'mengshen_pack-0080', 'artist:kagura_nana, 1.1::artist:petosu_(sunoco)::, 1.1::artist:greedice::, 1.1::artist:lukapia::, 1.1::artist:0lightsource::, 1.1::artist:yippee::'),
    ('梦神NAI4.5F画风合集 0081', 'mengshen_pack-0081', 'artist:kagura_nana, artist:game_cg, 0.4::artist:ie (raarami)::, 0.3::artist:shinjiro::, 0.5::artist:healthyman::, artist:8k_wallpaper'),
    ('梦神NAI4.5F画风合集 0082', 'mengshen_pack-0082', 'artist:kagura_nana, 1.2::artist:ishigaki takashi ::, 1.3::artist:ramanda ::, 0.5::artist:freng ::, 1.1::artist:sohn woohyoung ::, 1.1::artist:channel (caststation) ::'),
    ('梦神NAI4.5F画风合集 0083', 'mengshen_pack-0083', 'artist:kagura_nana, artist:mimulishizi, artist:rella, artist:murata_yuusuke, artist:messikid_1.15sweetonedollar, artist:takeshima_eku'),
    ('梦神NAI4.5F画风合集 0084', 'mengshen_pack-0084', 'artist:kagura_nana, 0.6::artist:ixy::, 0.95::artist:channel (caststaion)::, 1.1::artist:rekka_shinai::, 0.65::artist:satou kibi::, 0.85::artist:Henriiku (Ahemaru)::'),
    ('梦神NAI4.5F画风合集 0085', 'mengshen_pack-0085', 'artist:kagura_nana, 1.0::artist:teshima nari::, artist:konya karasue, 0.2::artist:ie (raarami)::, 0.4::artist:maeka (kumaekake)::, 0.5::artist:modare::'),
    ('梦神NAI4.5F画风合集 0086', 'mengshen_pack-0086', 'artist:kagura_nana, artist:kamitani_george, artist:mx2j, artist:hassan_(sink916), artist:hanpen kounaien, artist:en_0410'),
    ('梦神NAI4.5F画风合集 0087', 'mengshen_pack-0087', 'artist:kagura_nana, 0.8::artist:tomohiro kai ::, 0.3::artist:mizumizuni ::, 1.4::artist:wanke ::, 0.3::artist:kidmo ::, 1.5::artist:ask (askzy) ::'),
    ('梦神NAI4.5F画风合集 0088', 'mengshen_pack-0088', 'artist:kagura_nana, artist:chromatic_aberration, artist:amazing'),
    ('梦神NAI4.5F画风合集 0089', 'mengshen_pack-0089', 'artist:kagura_nana, artist:indie_virtual_youtuber, 1.2::artist:kaedeko (kaedelic) ::, 0.7::artist:rkrk12 ::, 0.9::artist:queasy s ::, 1.2::artist:sorapoi ::'),
    ('梦神NAI4.5F画风合集 0090', 'mengshen_pack-0090', 'artist:kagura_nana, artist:indie_virtual_youtuber, 1.5::artist:ratatatat74 ::, 1.2::artist:horikoshi_kouhei ::, 1.2::artist:ningen_mame ::, 0.7::artist:freng ::'),
    ('梦神NAI4.5F画风合集 0091', 'mengshen_pack-0091', 'artist:kagura_nana, artist:shiratama (shiratamaco), 1.5::artist:nao_(syn_eaa)::, 1.5::artist:mx2j ::, 1::artist:pigeon666 ::, 0.5::artist:waterkuma::'),
    ('梦神NAI4.5F画风合集 0092', 'mengshen_pack-0092', 'artist:kagura_nana, artist:indie_virtual_youtuber, artist:game_cg, artist:nihonga, artist:film_grain, artist:blurry'),
    ('梦神NAI4.5F画风合集 0093', 'mengshen_pack-0093', 'artist:kagura_nana, artist:bm94199, artist:nixeu, artist:slash_(slash-soft), artist:billyhhyb, artist:ruanjia'),
    ('梦神NAI4.5F画风合集 0094', 'mengshen_pack-0094', 'artist:kagura_nana, 1.2::artist:muchi maro ::, 0.8::artist:suga hideo ::, 0.3::artist:m-da s-tarou ::, 0.5::artist:collagen ::, 0.2::artist:tenako (mugu77) ::'),
    ('梦神NAI4.5F画风合集 0095', 'mengshen_pack-0095', 'artist:kagura_nana, 0.7::artist:jp06 ::, 0.8::artist:henriiku_(ahemaru)::, 0.6::artist:sohn_woohyoung::, 1.5::artist:ningen_mame ::, 0.4::artist:ratatatat74 ::'),
    ('梦神NAI4.5F画风合集 0096', 'mengshen_pack-0096', 'artist:kagura_nana, artist:flat_color, artist:cel_shading, artist:raytracing, artist:high_constrast, artist:shiny_skin'),
    ('梦神NAI4.5F画风合集 0097', 'mengshen_pack-0097', 'artist:kagura_nana, artist:heripiro, artist:omochi_monaka, artist:kyuumura, artist:tianliang_duohe_fangdongye, artist:fenrir_(fenriluuu)'),
    ('梦神NAI4.5F画风合集 0098', 'mengshen_pack-0098', 'artist:kagura_nana, artist:hyuk_(yeayeo), artist:mochirong, 0.8::artist:khyle. ::, artist:kekemotsu, artist:mocha_(cotton)'),
    ('梦神NAI4.5F画风合集 0099', 'mengshen_pack-0099', 'artist:kagura_nana, 0.6::artist:wagashi (dagashiya)::, 1::artist:healthyman ::, 1.2::artist:yamamoto souichirou ::, artist:oekaki, artist:color'),
    ('梦神NAI4.5F画风合集 0100', 'mengshen_pack-0100', 'artist:kagura_nana, artist:low_resolution, 1::Artist:loah66::, 1::artist:anmi::, artist:loah66, 0.7::artist:freng::'),
    ('梦神NAI4.5F画风合集 0101', 'mengshen_pack-0101', 'artist:kagura_nana, artist:hintobento, artist:etsuzan_jakusui, artist:broccoli_(broccoli2626), artist:pija_(pianiishimo), artist:dokuro-san'),
    ('梦神NAI4.5F画风合集 0102', 'mengshen_pack-0102', 'artist:kagura_nana, 0.3::artist:kidmo ::, 0.8::artist:freng::, 1.05::artist:sumiyao (amam)::, 0.7::artist:fanteam::, 0.4::artist:mikozin ::'),
    ('梦神NAI4.5F画风合集 0103', 'mengshen_pack-0103', 'artist:kagura_nana, [[artist:ritzchrono]], [[[artist:wagashi (dagashiya)]]], [[artist:mx2j]], artist:amazing'),
    ('梦神NAI4.5F画风合集 0104', 'mengshen_pack-0104', 'artist:kagura_nana, 1::artist:soso (chlgksk110)::, 1::artist:fujieda uzuki::, 1::artist:wagashi (dagashiya)::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0106', 'mengshen_pack-0106', 'artist:kagura_nana, 0.85::artist:healthyman::, artist:1boy, artist:pov, artist:from_below, artist:close-up'),
    ('梦神NAI4.5F画风合集 0107', 'mengshen_pack-0107', 'artist:kagura_nana, 1.1::artist:misaka_12003-gou ::, artist:loliconder, artist:nonco, 1.4::artist:healthyman ::, 1.1::artist:yoneyama mai ::'),
    ('梦神NAI4.5F画风合集 0108', 'mengshen_pack-0108', 'artist:kagura_nana, artist:mx2j, {artist:healthyman}, [[artist:dishwasher1910]], [[[artist:ningen mame]]], [[[artist:jonpei]]]'),
    ('梦神NAI4.5F画风合集 0109', 'mengshen_pack-0109', 'artist:kagura_nana, 0.7::artist:freng ::, 0.7::artist:modare ::, 1.0::artist:blue gk ::, 1.3::artist:mx2j ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0110', 'mengshen_pack-0110', 'artist:kagura_nana, 0.3::artist:cola gotouryouta::, 0.5::artist:yoneyama mai::, 0.7::artist:betabeet::, 0.9::artist:re0n::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0111', 'mengshen_pack-0111', 'artist:kagura_nana, 1.5::artist:gachigachi ::, artist:ataruman, 0.4::artist:ogipote ::, 0.7::artist:dorontabi ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0112', 'mengshen_pack-0112', 'artist:kagura_nana, 0.7::artist:qiandaiyiyu ::, 0.5::artist:shexyo ::, 1.3::artist:ratatatat74 ::, 0.9::artist:healthyman ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0113', 'mengshen_pack-0113', 'artist:kagura_nana, 1.2::artist:sumiyao (amam)::, 0.7::artist:mignon::, 0.4::artist:mikozin ::, 1.1::artist:mannack::, 1.2::artist:ie_(raarami)::'),
    ('梦神NAI4.5F画风合集 0114', 'mengshen_pack-0114', 'artist:kagura_nana, 1.4::artist:wanke ::, 0.3::artist:kidmo ::, 1.5::artist:ask (askzy) ::, 0.7::artist:freng ::, 0.7::artist:ratatatat74 ::'),
    ('梦神NAI4.5F画风合集 0115', 'mengshen_pack-0115', 'artist:kagura_nana, 1.1::artist:ohisashiburi ::, 0.89::artist:healthyman ::, 0.51::artist:misaka 12003-gou ::, 0.47::artist:qiandaiyiyu ::, 0.69::artist:ratatatat74 ::'),
    ('梦神NAI4.5F画风合集 0116', 'mengshen_pack-0116', 'artist:kagura_nana, 1.4::artist:healthyman ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0117', 'mengshen_pack-0117', 'artist:kagura_nana, artist:wagashi_(dagashiya), artist:wlop, 0.4::artist:ratatatat74 ::, artist:healthyman, artist:amazing'),
    ('梦神NAI4.5F画风合集 0118', 'mengshen_pack-0118', 'artist:kagura_nana, 1.5::artist:fungi542 ::, 0.69::artist:au (d elete) ::, 0.74::artist:john kafka ::, 0.3::artist:shexyo ::, 1.2::artist:alterkyon ::'),
    ('梦神NAI4.5F画风合集 0119', 'mengshen_pack-0119', 'artist:kagura_nana, 0.8::artist:shinjiro::, 0.5::artist:wagashi (dagashiya)::, artist:artist_collaboration, artist:flat_color, artist:signature__-1_dark_areolae'),
    ('梦神NAI4.5F画风合集 0120', 'mengshen_pack-0120', 'artist:kagura_nana, 1.3::artist:rei (sanbonzakura) ::, 0.5::artist:crab d ::, 0.4::artist:shexyo ::, 0.7::artist:saeuchobab ::, 1.5::artist:cherrymaru ::'),
    ('梦神NAI4.5F画风合集 0121', 'mengshen_pack-0121', 'artist:kagura_nana, artist:wagashi_(dagashiya), 0.4::artist:ratatatat74 ::, artist:healthyman, artist:flat_color, artist:amazing'),
    ('梦神NAI4.5F画风合集 0122', 'mengshen_pack-0122', 'artist:kagura_nana, 1.1::artist:wagashi (dagashiya) ::, 1.2::artist:sugoihi ::, 1.2::artist:ronna ::, 0.8::artist:asanagi ::, 0.9::artist:kanabun ::'),
    ('梦神NAI4.5F画风合集 0123', 'mengshen_pack-0123', 'artist:kagura_nana, artist:gsusart, artist:gogalking, artist:artist_collaboration, artist:amazing'),
    ('梦神NAI4.5F画风合集 0124', 'mengshen_pack-0124', 'artist:kagura_nana, 1.5::artist:almondman::, 1.4::artist:ie::, 1.3::artist:kawakami_rokkaku::, 1.2::artist:tianliang_duohe_fangdongye::, 1.1::artist:freng::'),
    ('梦神NAI4.5F画风合集 0125', 'mengshen_pack-0125', 'artist:kagura_nana, artist:ushikani_kassen, artist:sos_adult, artist:ikuchan_kaoru, artist:feipin_zhanshi, artist:chigusa_minori'),
    ('梦神NAI4.5F画风合集 0126', 'mengshen_pack-0126', 'artist:kagura_nana, artist:Paul Bonner, artist:Mike Lim, artist:Craig Mullins, artist:Yuki Yoshikawa, artist:tianliang duohe fangdongye'),
    ('梦神NAI4.5F画风合集 0127', 'mengshen_pack-0127', 'artist:kagura_nana, 1.5::artist:wagashi (dagashiya) ::, 0.7::artist:barbarian tk ::, 1.2::artist:ohisashiburi ::, 0.7::artist:remsrar ::, artist:cura'),
    ('梦神NAI4.5F画风合集 0128', 'mengshen_pack-0128', 'artist:kagura_nana, 0.5::artist:rei (sanbonzakura) ::, 0.8::artist:john kafka ::, 0.6::artist:mika pikazo ::, artist:flat_color, artist:colorful'),
    ('梦神NAI4.5F画风合集 0129', 'mengshen_pack-0129', 'artist:kagura_nana, 1.1::artist:ask (askzy) ::, 0.3::artist:henriiku (ahemaru) ::, 0.9::artist:lam (ramdayo) ::, artist:flat_color, artist:amazing'),
    ('梦神NAI4.5F画风合集 0130', 'mengshen_pack-0130', 'artist:kagura_nana, artist:freng, artist:iwao, artist:modare, artist:poper_(arin_sel), artist:amazing'),
    ('梦神NAI4.5F画风合集 0131', 'mengshen_pack-0131', 'artist:kagura_nana, artist:healthyman, artist:wlop, artist:kidmo, {artist:ratatatat74}, artist:iuui'),
    ('梦神NAI4.5F画风合集 0132', 'mengshen_pack-0132', 'artist:kagura_nana, 1.5::artist:ponsuke (pon00000)::, 1.5::artist:Higashiyama Shou::, 1.5::artist:custom udon::, 0.8::artist:barbarian tk::, 0.5::artist:diathorn::'),
    ('梦神NAI4.5F画风合集 0134', 'mengshen_pack-0134', 'artist:kagura_nana, 1.1::artist:ratatatat74 ::, 0.5::artist:fajyobore ::, 1.2::artist:john kafka ::, 1.4::artist:healthyman ::, artist:colorful'),
    ('梦神NAI4.5F画风合集 0135', 'mengshen_pack-0135', 'artist:kagura_nana, {{artist:gomzi}}, {artist:mx2j}, artist:healthyman, artist:pomu(joynet), artist:amazing'),
    ('梦神NAI4.5F画风合集 0137', 'mengshen_pack-0137', 'artist:kagura_nana, artist:asanagi, artist:loliconder, artist:kase daiki, artist:tedain, artist:dagashi_(wagashiya)'),
    ('梦神NAI4.5F画风合集 0138', 'mengshen_pack-0138', 'artist:kagura_nana, artist:healthyman, artist:ame (uten cancel), artist:xiao lin jiu, artist:amazing'),
    ('梦神NAI4.5F画风合集 0139', 'mengshen_pack-0139', 'artist:kagura_nana, 1.2::artist:onono imoko::, 1::artist:dorontabi::, 0.2::artist:hiro_(dismaless)::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0141', 'mengshen_pack-0141', 'artist:kagura_nana, artist:mx2j, 0.75::artist:sumiyao (amam) ::, 0.5::artist:wagashi (dagashiya) ::, 0.6::artist:freng ::, 0.9::artist:furau ::'),
    ('梦神NAI4.5F画风合集 0142', 'mengshen_pack-0142', 'artist:kagura_nana, artist:healthyman, 0.6::artist:usashiro mani ::, artist:ame (uten cancel), artist:xiao lin jiu, artist:amazing'),
    ('梦神NAI4.5F画风合集 0143', 'mengshen_pack-0143', 'artist:kagura_nana, artist:wolrero, artist:namaonpa, 0.6::artist:bee (deadflow)::, 1.5::artist:solipsist::, artist:vivid_colors'),
    ('梦神NAI4.5F画风合集 0144', 'mengshen_pack-0144', 'artist:kagura_nana, artist:sonao, 1.1::artist:healthyman::, artist:sparrowl, artist:wagashi_(dagashiya), artist:amazing'),
    ('梦神NAI4.5F画风合集 0145', 'mengshen_pack-0145', 'artist:kagura_nana, 1.4::artist:guchico ::, 0.8::artist:parsley-f ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0146', 'mengshen_pack-0146', 'artist:kagura_nana, 1.4::artist:sugoihi ::, 1.2::artist:ronna ::, 0.9::artist:kanabun ::, 1.2::artist:kanzarin ::, 0.9::artist:maud0239 ::'),
    ('梦神NAI4.5F画风合集 0147', 'mengshen_pack-0147', 'artist:kagura_nana, 0.9::artist:kink (tortoiseshell) ::, 1.1::artist:houkisei ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0148', 'mengshen_pack-0148', 'artist:kagura_nana, 0.8::artist:hxxg ::, 0.8::artist:quasarcake ::, 0.8::artist:mika pikazo ::, 1.2::artist:liduke ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0149', 'mengshen_pack-0149', 'artist:kagura_nana, 1.3::artist:myung yi ::, 1.0::artist:dishwasher1910 ::, 1.1::artist:yoneyama mai ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0150', 'mengshen_pack-0150', 'artist:kagura_nana, artist:taesi, artist:pinkmill, artist:mignon, artist:hidis0086, artist:amazing'),
    ('梦神NAI4.5F画风合集 0152', 'mengshen_pack-0152', 'artist:kagura_nana, 1.2::artist:xiujia yihuizi ::, 1.3::artist:yuki (asayuki101) ::, artist:mx2j, 0.8::artist:shigure s ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0153', 'mengshen_pack-0153', 'artist:kagura_nana, artist:sumiyao_(amam), artist:eonsang, artist:onono_imoko, artist:mignon, artist:kyokucho'),
    ('梦神NAI4.5F画风合集 0154', 'mengshen_pack-0154', 'artist:kagura_nana, artist:game_cg, artist:amazing'),
    ('梦神NAI4.5F画风合集 0155', 'mengshen_pack-0155', 'artist:kagura_nana, {artist:mochirong}, [[[artist:hepari]]], {artist:kawakami rokkaku}, [[[artist:henry bird 9]]], {artist:djheycha}'),
    ('梦神NAI4.5F画风合集 0156', 'mengshen_pack-0156', 'artist:kagura_nana, 0.5::artist:au_(d_elete)::, 1::artist:onono imoko::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0157', 'mengshen_pack-0157', 'artist:kagura_nana, 1.0::artist:akiyama enma::, 1.0::artist:freng::, 0.7::artist:gorgeous mushroom::, 0.4::artist:qiandaiyiyu::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0159', 'mengshen_pack-0159', 'artist:kagura_nana, artist:flasso, [[artist:puddinghomhom]], artist:suye, artist:nashidrop, artist:taotao'),
    ('梦神NAI4.5F画风合集 0160', 'mengshen_pack-0160', 'artist:kagura_nana, 1.2::artist:torriet::, artist:wagashi_(dagashiya), artist:ronna, artist:healthyman, artist:amazing'),
    ('梦神NAI4.5F画风合集 0161', 'mengshen_pack-0161', 'artist:kagura_nana, artist:pyon-kichi, 1.5::artist:mendou kusai ::, artist:game_cg, artist:blender_(medium), artist:amazing'),
    ('梦神NAI4.5F画风合集 0162', 'mengshen_pack-0162', 'artist:kagura_nana, 0.9::artist:try (lsc) ::, 0.8::artist:gaou (umaiyo puyoman) ::, 0.6::artist:null (nyanpyoun) ::, 0.75::artist:murata yuusuke ::, 1.2::artist:sonao ::'),
    ('梦神NAI4.5F画风合集 0163', 'mengshen_pack-0163', 'artist:kagura_nana, [artist:nakta], {{artist:sumiyao}}, [[[artist:yutokamizu]]], [[artist:choco (chocolate shop)]], artist:amazing'),
    ('梦神NAI4.5F画风合集 0164', 'mengshen_pack-0164', 'artist:kagura_nana, 1::artist:fkey ::, artist:massakasama, 1.5::artist:solipsist ::, artist:ligne_claire, artist:sketch'),
    ('梦神NAI4.5F画风合集 0165', 'mengshen_pack-0165', 'artist:kagura_nana, artist:kajimakoto, 0.6::artist:menthako ::, 0.6::artist:tianliangduohe fangdongye ::, 1.1::artist:crybaby ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0167', 'mengshen_pack-0167', 'artist:kagura_nana, 1.5::artist:solipsist ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0168', 'mengshen_pack-0168', 'artist:kagura_nana, 0.5::artist:shexyo::, 1.5::artist:fungi542 ::, 0.9::artist:john kafka ::, artist:wagashi_(dagashiya), 1.3::artist:patch oxxo ::'),
    ('梦神NAI4.5F画风合集 0169', 'mengshen_pack-0169', 'artist:kagura_nana, artist:blender_(medium), artist:no_lineart, 1.2::artist:musouzuki ::, artist:momoco, 0.8::artist:pottsness ::'),
    ('梦神NAI4.5F画风合集 0170', 'mengshen_pack-0170', 'artist:kagura_nana, 1.33::artist:beeeeen ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0171', 'mengshen_pack-0171', 'artist:kagura_nana, artist:maki_keigo, artist:mountain_han, artist:konoshige_(ryuun), artist:akino_sora, artist:hiro_(dismaless)'),
    ('梦神NAI4.5F画风合集 0172', 'mengshen_pack-0172', 'artist:kagura_nana, artist:nyte tyde, artist:96yottea, artist:amazing'),
    ('梦神NAI4.5F画风合集 0173', 'mengshen_pack-0173', 'artist:kagura_nana, 1.4::artist:null (nyanpyoun)::, artist:zankuro, artist:blue_gk, 1.5::artist:patimon::, 1.5::artist:xipa::'),
    ('梦神NAI4.5F画风合集 0174', 'mengshen_pack-0174', 'artist:kagura_nana, [[artist:ahemaru]], [artist:rikose], artist:amazing'),
    ('梦神NAI4.5F画风合集 0175', 'mengshen_pack-0175', 'artist:kagura_nana, artist:healthyman, 1.4::artist:hizuki akira ::, artist:quasarcake, 0.3::artist:null (nyanpyoun) ::, artist:doremi (doremi4704)'),
    ('梦神NAI4.5F画风合集 0176', 'mengshen_pack-0176', 'artist:kagura_nana, 1.5::artist:courreges ace::, artist:tsunako, artist:tatsuya (s6pillars), artist:amazing'),
    ('梦神NAI4.5F画风合集 0177', 'mengshen_pack-0177', 'artist:kagura_nana, artist:wagashi (dagashiya), artist:shinjiro, artist:ie_(raarami), 0.4::artist:nakta::, 0.3::artist:healthyman::'),
    ('梦神NAI4.5F画风合集 0178', 'mengshen_pack-0178', 'artist:kagura_nana, 1.4::artist:freng ::, 0.7::artist:jonpei ::, 1.2::artist:quasarcake ::, artist:portrait, artist:location'),
    ('梦神NAI4.5F画风合集 0180', 'mengshen_pack-0180', 'artist:kagura_nana, 0.8::artist:miyuchiq::, 0.9::artist:tomoyoo::, 1.3::artist:otintinn::, 1.1::artist:fuukadia (narcolepsy)::, 0.6::artist:shigezie::'),
    ('梦神NAI4.5F画风合集 0181', 'mengshen_pack-0181', 'artist:kagura_nana, artist:gogalking, artist:akiyama_enma, artist:ratatatat74, artist:null_(nyanpyoun), 1.2::artist:channel (caststation) ::'),
    ('梦神NAI4.5F画风合集 0183', 'mengshen_pack-0183', 'artist:kagura_nana, 1.11::artist:hanekoto ::, 1.3::artist:yalmyu ::, 1.13::artist:mochirong ::, 1.22::artist:0202ase ::, 1.25::artist:myabit ::'),
    ('梦神NAI4.5F画风合集 0185', 'mengshen_pack-0185', 'artist:kagura_nana, 0.9::artist:tomoyoo::, 1.1::artist:fuukadia (narcolepsy)::, 1.2::artist:shigezie::, 0.7::artist:mamerakkkkko::, 0.8::artist:happa freee::'),
    ('梦神NAI4.5F画风合集 0187', 'mengshen_pack-0187', 'artist:kagura_nana, artist:ohisashiburi, artist:mx2j, artist:baffu, 1.1::artist:gamerag ::, 1.5::artist:ie (raarami) ::'),
    ('梦神NAI4.5F画风合集 0188', 'mengshen_pack-0188', 'artist:kagura_nana, 1.2::artist:possummachine::, 0.8::artist:tianliang duohe fangdongye::, 1::artist:muchi maro::, 0.6::artist:songchuan li::, 1::artist:subachi::'),
    ('梦神NAI4.5F画风合集 0189', 'mengshen_pack-0189', 'artist:kagura_nana, artist:tsunako, artist:ciloranko, artist:liumang_tu_shua_p_zhan, artist:Mika Pikazo, artist:atdan'),
    ('梦神NAI4.5F画风合集 0190', 'mengshen_pack-0190', 'artist:kagura_nana, artist:cel_shading, artist:flat_color, [artist:butakoma 300g], artist:jp06, 1.5::artist:kaisen_chuui::'),
    ('梦神NAI4.5F画风合集 0191', 'mengshen_pack-0191', 'artist:kagura_nana, artist:hanabushi, artist:artist_collaboration, artist:flat_color, artist:amazing'),
    ('梦神NAI4.5F画风合集 0192', 'mengshen_pack-0192', 'artist:kagura_nana, artist:healthyman, 0.6::artist:mamerakkkkko ::, artist:freng, artist:ame (uten cancel), artist:xiao lin jiu'),
    ('梦神NAI4.5F画风合集 0193', 'mengshen_pack-0193', 'artist:kagura_nana, 0.9::artist:ke-ta ::, 0.75::artist:sho (sho lwlw) ::, 0.6::artist:ciloranko ::, 1.5::artist:onono imoko ::, 0.9::artist:ningen mame ::'),
    ('梦神NAI4.5F画风合集 0194', 'mengshen_pack-0194', 'artist:kagura_nana, 1::artist:muchi maro::, 1.4::artist:imamura ryou::, 1.2::artist:possummachine::, 0.8::artist:tianliang duohe fangdongye::, 0.6::artist:songchuan li::'),
    ('梦神NAI4.5F画风合集 0195', 'mengshen_pack-0195', 'artist:kagura_nana, artist:sonao, 1.1::artist:healthyman::, artist:sparrowl, artist:wagashi_(dagashiya), artist:pastel_colors'),
    ('梦神NAI4.5F画风合集 0196', 'mengshen_pack-0196', 'artist:kagura_nana, 1.14::artist:shexyo ::, 1.21::artist:blue gk ::, artist:multiple_views, artist:amazing'),
    ('梦神NAI4.5F画风合集 0197', 'mengshen_pack-0197', 'artist:kagura_nana, 0.9::artist:try (lsc)::, 0.8::artist:gaou (umaiyo puyoman)::, 0.6::artist:null (nyanpyoun)::, 0.75::artist:murata yuusuke::, 1.2::artist:sonao::'),
    ('梦神NAI4.5F画风合集 0198', 'mengshen_pack-0198', 'artist:kagura_nana, artist:wagashi (dagashiya), 1.3::artist:imamura ryou::, 0.7::artist:ie (raarami)::, 1.2::artist:sparrowl::, artist:artist_collaboration'),
    ('梦神NAI4.5F画风合集 0199', 'mengshen_pack-0199', 'artist:kagura_nana, artist:hot vr, artist:merrytail, artist:kajimakoto, 0.8::artist:tianliang duohe fangdongye::, artist:freng'),
    ('梦神NAI4.5F画风合集 0200', 'mengshen_pack-0200', 'artist:kagura_nana, 1.5::artist:an_sin::, 1.5::artist:almondman::, 1.4::artist:ie::, 1.3::artist:kawakami_rokkaku::, 1.2::artist:tianliang_duohe_fangdongye::'),
    ('梦神NAI4.5F画风合集 0201', 'mengshen_pack-0201', 'artist:kagura_nana, 1.2::artist:dishwasher1910 ::, 1.5::artist:gogalking::, 0.4::artist:shiren (ourboy83)::, artist:mx2j, 1.1::artist:houtengeki::'),
    ('梦神NAI4.5F画风合集 0202', 'mengshen_pack-0202', 'artist:kagura_nana, artist:cel_shading, artist:nikubou_maranoshin, 1.2::artist:kawakami rokkaku::, artist:modare, artist:jp06'),
    ('梦神NAI4.5F画风合集 0203', 'mengshen_pack-0203', 'artist:kagura_nana, 0.8::artist:onono imoko ::, [artist:kanzarin], [[artist:krekkov]], artist:kusaremix, artist:momisan'),
    ('梦神NAI4.5F画风合集 0204', 'mengshen_pack-0204', 'artist:kagura_nana, artist:brush_stroke, artist:faux_traditional_media, 1.5::artist:zero q 0q::, 1.5::artist:solipsist::, 1.3::artist:tokiame ::'),
    ('梦神NAI4.5F画风合集 0205', 'mengshen_pack-0205', 'artist:kagura_nana, artist:agwing86, artist:healthyman, artist:dorontabi, artist:miyako (naotsugu), artist:amazing'),
    ('梦神NAI4.5F画风合集 0206', 'mengshen_pack-0206', 'artist:kagura_nana, artist:oekaki, artist:aliasing, 1.3::artist:yamamoto souichirou::, artist:dorontabi, artist:teshima nari'),
    ('梦神NAI4.5F画风合集 0207', 'mengshen_pack-0207', 'artist:kagura_nana, 0.3::artist:agwing86 ::, artist:dorontabi, 1.3::artist:miyako (naotsugu)::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0209', 'mengshen_pack-0209', 'artist:kagura_nana, 0.8::artist:qiandaiyiyu::, 0.85::artist:aiue oka::, 0.9::artist:lunch (shin new)::, 1.1::artist:cola gotouryouta::, 1.3::artist:dishwasher1910 ::'),
    ('梦神NAI4.5F画风合集 0210', 'mengshen_pack-0210', 'artist:kagura_nana, 0.75::artist:lunch (shin new)::, 0.8::artist:modare::, 1.15::artist:momoko (momopoco)::, 1.2::artist:yoya yogurt::, 1.25::artist:cola gotouryouta::'),
    ('梦神NAI4.5F画风合集 0211', 'mengshen_pack-0211', 'artist:kagura_nana, 0.8::artist:qiandaiyiyu::, 0.95::artist:hyulla::, 1.0::artist:cola gotouryouta::, 1.1::artist:alp::, 1.15::artist:shinjiro::'),
    ('梦神NAI4.5F画风合集 0212', 'mengshen_pack-0212', 'artist:kagura_nana, 0.8::artist:dorontabi ::, 0.7::artist:ame (uten cancel) ::, artist:hyper_detail, artist:8k_render, artist:expert_shading'),
    ('梦神NAI4.5F画风合集 0214', 'mengshen_pack-0214', 'artist:kagura_nana, artist:waero, artist:deyui, artist:anoyo_(anoyode0), artist:mzet, artist:berryverrine'),
    ('梦神NAI4.5F画风合集 0215', 'mengshen_pack-0215', 'artist:kagura_nana, [[artist:basukechi ]], [[artist:freng ]], [artist:wagashi_(dagashiya)], artist:amazing'),
    ('梦神NAI4.5F画风合集 0217', 'mengshen_pack-0217', 'artist:kagura_nana, 1.5::artist:healthyman ::, 1.1::artist:wagashi (dagashiya) ::, 1.5::artist:barbarian tk ::, 0.9::artist:tianliang duohe fangdongye ::, 0.8::artist:robo mikan ::'),
    ('梦神NAI4.5F画风合集 0218', 'mengshen_pack-0218', 'artist:kagura_nana, 1.2::artist:bacius::, artist:matado (almukha), 1.5::artist:rurudo ::, 0.6::artist:mignon ::, 0.9::artist:tianliang duohe fangdongye::'),
    ('梦神NAI4.5F画风合集 0219', 'mengshen_pack-0219', 'artist:kagura_nana, artist:mato_tsuyoi, 0.5::artist:mika pikazo ::, 1.5::artist:kenkou cross ::, 1.4::artist:chamchami ::, 0.9::artist:ciloranko ::'),
    ('梦神NAI4.5F画风合集 0220', 'mengshen_pack-0220', 'artist:kagura_nana, 1.5::artist:wagashi(dagashiya)::, 1.5::artist:iwano kenta::, 1.5::artist:yamaori::, artist:kakure eria, artist:asanagi'),
    ('梦神NAI4.5F画风合集 0221', 'mengshen_pack-0221', 'artist:kagura_nana, 1.5::artist:ohisashiburi::, artist:watao, artist:mx2j, 0.5::artist:ningen mame::, 0.7::artist:gogalking::'),
    ('梦神NAI4.5F画风合集 0222', 'mengshen_pack-0222', 'artist:kagura_nana, artist:healthyman, artist:wagashi_(dagashiya), 0.7::artist:mochirong::, 0.6::artist:ie (raarami)::, 0.8::artist:imamura ryou::'),
    ('梦神NAI4.5F画风合集 0223', 'mengshen_pack-0223', 'artist:kagura_nana, 1.3::artist:healthyman ::, 0.6::artist:sangobob ::, 0.8::artist:tianliang duohe fangdongye ::, 0.8::artist:freng ::, 0.6::artist:null (nyanpyoun) ::'),
    ('梦神NAI4.5F画风合集 0224', 'mengshen_pack-0224', 'artist:kagura_nana, artist:an sin, artist:ciloranko, artist:healthyman, artist:lunch (shin new), artist:shinjiro'),
    ('梦神NAI4.5F画风合集 0225', 'mengshen_pack-0225', 'artist:kagura_nana, 1.2::artist:yamamoto souichirou ::, 0.7::artist:ciloranko ::, 1.0::artist:channel (caststation)::, 1.1::artist:ratatat74 ::, 1.1::artist:gogalking ::'),
    ('梦神NAI4.5F画风合集 0226', 'mengshen_pack-0226', 'artist:kagura_nana, 0.8::artist:toma (toma50)::, 0.5::artist:96yottea::, 0.9::artist:channel (caststation)::, artist:humed_skin, artist:amazing'),
    ('梦神NAI4.5F画风合集 0228', 'mengshen_pack-0228', 'artist:kagura_nana, 0.5::artist:mika pikazo::, 0.55::artist:cocoballking::, 0.7::artist:teshima nari::, 0.85::artist:ratatatat74 ::, 0.9::artist:meme50 ::'),
    ('梦神NAI4.5F画风合集 0229', 'mengshen_pack-0229', 'artist:kagura_nana, artist:ketsu_juuji_killer_(kejuki), artist:nekoshoko, 0.4::artist:chamchami::, 0.84::artist:hth5k::, artist:jinzai_5'),
    ('梦神NAI4.5F画风合集 0230', 'mengshen_pack-0230', 'artist:kagura_nana, 0.4::artist:mirin chikuwa ::, artist:pija_(pianiishimo), 0.4::artist:shiokonbu ::, artist:ikuchan_kaoru, 0.5::artist:collagen ::'),
    ('梦神NAI4.5F画风合集 0231', 'mengshen_pack-0231', 'artist:kagura_nana, artist:motsuaki, artist:shinjiro, 0.1::artist:shexyo::, artist:mochirong, artist:freng'),
    ('梦神NAI4.5F画风合集 0232', 'mengshen_pack-0232', 'artist:kagura_nana, artist:aduare, artist:philipp_urlich, artist:abysswolf, artist:namako_daibakuhatsu, artist:shirosu'),
    ('梦神NAI4.5F画风合集 0233', 'mengshen_pack-0233', 'artist:kagura_nana, 0.5::artist:kezime ::, 1.5::artist:blueborscht ::, 1::artist:yabby ::, 1.3::artist:imamura ryou::, 0.7::artist:ie (raarami)::'),
    ('梦神NAI4.5F画风合集 0234', 'mengshen_pack-0234', 'artist:kagura_nana, 0.65::artist:egami ::, artist:totomono, 0.48::artist:wakame (vhai26uhykmqb9k) ::, 0.8::artist:waterkuma ::, 0.45::artist:tianliang duohe fangdongye ::'),
    ('梦神NAI4.5F画风合集 0235', 'mengshen_pack-0235', 'artist:kagura_nana, 1.5::artist:healthyman ::, 1.1::artist:danimaru ::, 1.2::artist:tatami to hinoki ::, 0.8::artist:ningen mame ::, 0.9::artist:quasarcake ::'),
    ('梦神NAI4.5F画风合集 0236', 'mengshen_pack-0236', 'artist:kagura_nana, 1.5::artist:gogalking ::, 0.9::artist:ayuma_sayu ::, artist:ratatatat74, artist:eonsang, artist:freng'),
    ('梦神NAI4.5F画风合集 0237', 'mengshen_pack-0237', 'artist:kagura_nana, 0.9::artist:kanzarin ::, 1.1::artist:yamamoto souichirou ::, 1.4::artist:azmira1534815 ::, 0.9::artist:tianliang duohe fangdongye ::, 0.8::artist:erere ::'),
    ('梦神NAI4.5F画风合集 0238', 'mengshen_pack-0238', 'artist:kagura_nana, artist:healthyman, artist:wagashi_(dagashiya), 0.7::artist:mochirong ::, 0.6::artist:ie (raarami) ::, 0.8::artist:imamura ryou ::'),
    ('梦神NAI4.5F画风合集 0239', 'mengshen_pack-0239', "artist:kagura_nana, artist:healthyman, artist:shaddai, artist:wagashi_(dagashiya), artist:ebora_', artist:game_cg"),
    ('梦神NAI4.5F画风合集 0240', 'mengshen_pack-0240', 'artist:kagura_nana, 0.6::artist:ebifurya ::, 0.7::artist:freng ::, 1.3::artist:doremi (doremi4704) ::, 1.1::artist:quasarcake ::, artist:cherry_blossom_petals'),
    ('梦神NAI4.5F画风合集 0241', 'mengshen_pack-0241', 'artist:kagura_nana, artist:sonao, 1.1::artist:healthyman ::, artist:sparrowl, artist:wagashi_(dagashiya), artist:freng'),
    ('梦神NAI4.5F画风合集 0242', 'mengshen_pack-0242', 'artist:kagura_nana, artist:sumiyao (amam), artist:healthyman, 0.2::artist:misaka 12003-gou ::, 0.5::artist:mika pikazo ::, 0.8::artist:ratatatat74 ::'),
    ('梦神NAI4.5F画风合集 0243', 'mengshen_pack-0243', 'artist:kagura_nana, 0.4::artist:toono_esuke::, 0.6::artist:momonosuke_(u-ma991028)::, 1.3::artist:freng::, 0.9::artist:pepq::, 1.2::artist:marron_marron::'),
    ('梦神NAI4.5F画风合集 0244', 'mengshen_pack-0244', 'artist:kagura_nana, 0.6::artist:berryverrine::, 1.1::artist:Borushichi::, 1::artist:ask_(askzy)::, artist:ddal, 1.1::artist:lumo_1121 ::'),
    ('梦神NAI4.5F画风合集 0245', 'mengshen_pack-0245', 'artist:kagura_nana, 0.6::artist:kakure eria::, artist:wagashi_(dagashiya), 0.6::artist:ie (raarami)::, 0.6::artist:kedama_milk::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0246', 'mengshen_pack-0246', 'artist:kagura_nana, [artist:halcon], [[[artist:fuooooo]]], [[[artist:nakatama kyou]]], artist:ciloranko, {{artist:j.k.}}'),
    ('梦神NAI4.5F画风合集 0247', 'mengshen_pack-0247', 'artist:kagura_nana, 1.1::artist:yamamoto souichirou ::, 0.9::artist:tianliang duohe fangdongye ::, 1.2::artist:maud0239 ::, artist:amazing'),
    ('梦神NAI4.5F画风合集 0249', 'mengshen_pack-0249', 'artist:kagura_nana, artist:m-da_s-tarou, artist:sugoihi, artist:maruko_tooto, artist:ipuu_(el-ane_koubou), artist:amazing'),
    ('梦神NAI4.5F画风合集 0251', 'mengshen_pack-0251', 'artist:kagura_nana, 0.6::artist:null (nyanpyoun)::, 0.9::artist:try (lsc)::, 0.8::artist:gaou (umaiyo puyoman)::, 1.2::artist:sonao::, 1.05::artist:kokosando::'),
    ('梦神NAI4.5F画风合集 0252', 'mengshen_pack-0252', 'artist:kagura_nana, artist:Artists2satou_kuuki, artist:binggong_asylum, artist:mankai_kaika, artist:nakata_gorori, artist:sos_adult'),
    ('梦神NAI4.5F画风合集 0255', 'mengshen_pack-0255', 'artist:kagura_nana, artist:arato_asato, artist:ratatatat74, artist:eonsang, artist:freng, artist:null_(nyanpyoun)'),
    ('梦神NAI4.5F画风合集 0256', 'mengshen_pack-0256', 'artist:kagura_nana, artist:sos_adult, artist:flasso, artist:kobinbin, artist:mikozin, artist:fan_no_hitori'),
    ('梦神NAI4.5F画风合集 0257', 'mengshen_pack-0257', 'artist:kagura_nana, artist:astg, artist:mignon, artist:amazing'),
    ('冰蓝柔光（日系）', 'preset:iceblue', '0.45::artist:pan_(mimi)::, 0.6::artist:skinfang::, 0.7::artist:hoshi_(snacherubi)::, 0.75::artist:comodox::, 0.8::artist:chen_bin::'),
    ('冷调电影厚涂', 'preset:cinematic', '0.9::artist:wlop::, 0.3::artist:domo_(domokizusuki)::, 1.1::artist:au_(d_elete)::'),
    ('冷调电影厚涂', 'preset:cinematic', 'artist:murata_yuusuke, 1.05::artist:tianliang_duohe_fangdongye::, 0.95::artist:ciloranko::, 0.95::artist:ningen_mame::, 0.95::artist:healthyman::'),
    ('冷调电影厚涂', 'preset:cinematic', 'artist:ningen_mame, artist:mika_pikazo, [artist:reoen], [artist:tianliang_duohe_fangdongye], [artist:kantoku]'),
    ('霓虹平涂', 'preset:neon_flat', '1.2::artist:vanripper::, 0.8::artist:batrobin_k::, 0.5::artist:take_(illustrator)::, 0.5::artist:j.k.::, 0.4::artist:jtveemo::'),
    ('霓虹平涂', 'preset:neon_flat', '1.16::artist:kedama_milk::, 0.86::artist:mika_pikazo::, [artist:ciloranko], [artist:reoen]'),
    ('霓虹平涂', 'preset:neon_flat', '0.8::artist:furau::, 0.75::artist:wagashi_(dagashiya)::, 0.9::artist:deadflow::, [artist:mx2j]'),
    ('高光成熟人物', 'preset:glossy_mature', '0.95::artist:healthyman::, 0.9::artist:modare::, 0.85::artist:fuzichoco::, 0.85::artist:wanke::, [artist:ciloranko]'),
    ('高光成熟人物', 'preset:glossy_mature', '1.3::artist:wagashi_(dagashiya)::, artist:wlop, 0.4::artist:ratatatat::, 0.7::artist:imamura_ryou::, [artist:healthyman]'),
    ('高光成熟人物', 'preset:glossy_mature', '0.8::artist:furau::, 0.75::artist:wagashi_(dagashiya)::, 0.9::artist:deadflow::, 1.2::artist:mdf_an::, [artist:freng]'),
    ('暗夜轻熟肖像', 'preset:dark_portrait', '0.7::artist:ciloranko::, 0.6::artist:mika_pikazo::, 0.5::artist:mx2j::, 0.5::artist:dramz::, artist:96yottea'),
    ('暗夜轻熟肖像', 'preset:dark_portrait', 'artist:ciloranko, 0.95::artist:sho_(sho_lwlw)::, 0.91::artist:tianliang_duohe_fangdongye::, 0.74::artist:kani_biimu::'),
    ('暗夜轻熟肖像', 'preset:dark_portrait', 'artist:ningen_mame, artist:mika_pikazo, [artist:reoen], [artist:tianliang_duohe_fangdongye], [artist:ask_(askzy)], [artist:kantoku]'),
    ('暗夜轻熟肖像', 'preset:dark_portrait', '1.16::artist:kedama_milk::, 0.86::artist:mika_pikazo::, [artist:ciloranko], [artist:sho_(sho_lwlw)]'),
    ('暖金逆光', 'preset:golden_backlight', '0.3::artist:toosaka_asagi::, 0.3::artist:miv4t::, 0.3::artist:huashijw::, 0.1::artist:quasarcake::, artist:hibioes, artist:konya_karasue, artist:rella'),
    ('暮光花境', 'preset:dreamy_floral', 'artist:ichigoyama, artist:ashima_(roro046), artist:rella, artist:onineko'),
    ('青雾胶片插画', 'preset:filmgrain_illustration', 'artist:chen_bin, 0.7::artist:fuzichoco::, 0.7::artist:reoen::, 0.6::artist:tianliang_duohe_fangdongye::, 0.5::artist:mikozin::'),
)
